name: melon-ticket

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 213025
          schedule-id: 100001
          seat-id: 1_0
          message: '🎫 有票了！'
          disable-slack: true   # 👈 关键！！加这一行
